### ISSUE TITLE
load tract groups file - pick tracts

### ISSUE THREAD

**Issue by tinabehdinan** [ljod/whitematteranalysis#11]
Hi - I'm a Master's student in Dr. Voineskos' Lab at the Centre for Addiction and Mental Health. I've been working with your new white matter analysis pipeline and I've encountered a problem when loading the tract groups file into pick tracts. My steps were as follows:
1. Open MRML file in slicer4
2. Create new group (uncinate fasciculus)
3. Select clusters for this group
4. Create new group (inferior fronto-occipital fasciculus)
5. Select clusters for this group. Repeated these steps for the arcuate and inferior longitudinal fasciculus.

At this point I had to close and reopen slicer on a different computer. 

6. Save tract groups .txt file and close slicer
7. Reopen MRML file in slicer
8. Load tract groups .txt file

Unfortunately, the clusters I'd selected were no longer associated with the original tract. When viewing a tract, the clusters for all tracts were visible and I could no longer discern the separate tracts. I was wondering if there was a way around this problem, and I would really appreciate your help with this! 

Thank you,

Tina

**Comment by ljod** [comment]
Hi Tina!
We've done a lot of work on this and we are now using the slicer hierarchy
functionality in slicer 4 nightly instead of pick tracts.

I have deadlines tomorrow but after that, say Friday afternoon, I can send
more information. We can also have a tcon next week if your group is
available.

The web instructions need to be updated to describe the new process.

Lauren

On Wednesday, January 14, 2015, tinabehdinan <notifications@github.com>
wrote:

> Hi - I'm a Master's student in Dr. Voineskos' Lab at the Centre for
> Addiction and Mental Health. I've been working with your new white matter
> analysis pipeline and I've encountered a problem when loading the tract
> groups file into pick tracts. My steps were as follows:
> 1. Open MRML file in slicer4
> 2. Create new group (uncinate fasciculus)
> 3. Select clusters for this group
> 4. Create new group (inferior fronto-occipital fasciculus)
> 5. Select clusters for this group. Repeated these steps for the arcuate
> and inferior longitudinal fasciculus.
>
> At this point I had to close and reopen slicer on a different computer.
>
>    1. Save tract groups .txt file and close slicer
>    2. Reopen MRML file in slicer
>    3. Load tract groups .txt file
>
> Unfortunately, the clusters I'd selected were no longer associated with
> the original tract. When viewing a tract, the clusters for all tracts were
> visible and I could no longer discern the separate tracts. I was wondering
> if there was a way around this problem, and I would really appreciate your
> help with this!
>
> Thank you,
>
> Tina
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ljod/whitematteranalysis/issues/11>.
>
> The information in this e-mail is intended only for the person to whom it
> is
> addressed. If you believe this e-mail was sent to you in error and the
> e-mail
> contains patient information, please contact the Partners Compliance
> HelpLine at
> http://www.partners.org/complianceline . If the e-mail was sent to you in
> error
> but does not contain patient information, please contact the sender and
> properly
> dispose of the e-mail.
>


-- 
Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by tinabehdinan** [comment]
Thanks Lauren. I look forward to hearing from you tomorrow and hopefully we can set up a time to talk more about how the pipeline works next week! 

Tina

**Comment by ljod** [comment]
Hi! I have several meetings this afternoon and I don't have time to
send you more documentation right now. Let's set a time to talk next week.
There are parameters to learn about and a new quality control script, etc.

How about Tuesday afternoon at 1pm via Skype?

Lauren


Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by ljod** [comment]
I'm laurenjod on Skype

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by tinabehdinan** [comment]
Sounds great! I will see you tomorrow at 1.

Thanks,

Tina
