### ISSUE TITLE
quality control error

### ISSUE THREAD

**Issue by tinabehdinan** [ljod/whitematteranalysis#12]
Hi Lauren,

I was just trying out the wm_quality_control_tractography.py script and it seems to start with one subject (H177) and then stop because of an error: 

```
/scratch/tinab/lauren_test2$ wm_quality_control_tractography.py input/ input_QCed
<quality_control> Starting...
<register> Output directory input_QCed does not exist, creating it.
<quality_control> Testing all vtk files for quality control (fiber length measurements and rendering to make sure header and gradient orientations are ok).
<quality_control> Found  7 subjects in input directory: input/
Subject  1 / 7 ID: H177_CAMH_TRACTS
<render.py> Initiating rendering.
<render.py> Downsampling vtkPolyData: 1000
Point data array found: FA1 1
Point data array found: EstimatedUncertainty 1
<filter.py> Fibers sampled: 1000 / 94254
<render.py> Rendering vtkPolyData.
<render.py> Render pipeline created.
<render.py> Saving rendered views to disk: input_QCed/tract_QC_H177_CAMH_TRACTS
<filter.py> Minimum length 100 mm. Tractography step size * minimum number of points = 0.899956079971 * 111.0 )
<filter.py> Fibers sampled: 15607 / 94254
<filter.py> Fibers sampled: 500 / 15607
<filter.py> Fibers sampled: 500 / 500
Traceback (most recent call last):
  File "/opt/quarantine/whitematteranalysis/2015-01-20/build/bin/wm_quality_control_tractography.py", line 130, in <module>
    appender.AddInputData(pd3)
AttributeError: AddInputData
<render.py> in DELETE
```

Thanks for taking the time to meet with us again!

Tina

**Comment by ljod** [comment]
Hi Tina.
Thanks for catching that. This is a vtk version bug--I will have to edit
that line to fix it.

Lauren


Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by ljod** [comment]
This should be fixed in the code now, if you update your
whitematteranalysis.

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu
