### ISSUE TITLE
Models module

### ISSUE THREAD

**Issue by tinabehdinan** [ljod/whitematteranalysis#13]
Hi Lauren,

Having another problem using the Models module in slicer4. From my understanding, I can drag and drop clusters into my "models" (or tracts) to create the hierarchy. With the Pick Tracts module, we were able to use the keyboard to select and deselect clusters to include in each tract group. Is there a similar function for the Models module, where we can select clusters by dragging the mouse over the 3D image? I just think this would be a more efficient and accurate way of clustering the atlas, and I wasn't able to find any information on the slicer wiki unfortunately so any help is much appreciated!

Thanks,

Tina

**Comment by ljod** [comment]
Nope. The interface is just drag and drop. I agree the other method is
nicer but it does not currently work with hierarchies, which are now fixed
and can work for measurement.



On Tuesday, January 20, 2015, tinabehdinan <notifications@github.com> wrote:

> Hi Lauren,
>
> Having another problem using the Models module in slicer4. From my
> understanding, I can drag and drop clusters into my "models" (or tracts) to
> create the hierarchy. With the Pick Tracts module, we were able to use the
> keyboard to select and deselect clusters to include in each tract group. Is
> there a similar function for the Models module, where we can select
> clusters by dragging the mouse over the 3D image? I just think this would
> be a more efficient and accurate way of clustering the atlas, and I wasn't
> able to find any information on the slicer wiki unfortunately so any help
> is much appreciated!
>
> Thanks,
>
> Tina
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ljod/whitematteranalysis/issues/13>.
>
> The information in this e-mail is intended only for the person to whom it
> is
> addressed. If you believe this e-mail was sent to you in error and the
> e-mail
> contains patient information, please contact the Partners Compliance
> HelpLine at
> http://www.partners.org/complianceline . If the e-mail was sent to you in
> error
> but does not contain patient information, please contact the sender and
> properly
> dispose of the e-mail.
>


-- 
Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by pipitone** [comment]
Hmm, here's what we're thinking as a workaround for now: use PickTracts to create groups of clusters, and I'll write a small converter that dumps out a MRML file compatible with hierarchies.

**Comment by ljod** [comment]
Sounds fine. That is the desired output of pick tracts but previously the
slicer hierarchies did not work for tracts, so our work has been on making
that work. It would be great if you can create the hierarchy in the pick
tracts module. That would be helpful for us as well.

On Wednesday, January 21, 2015, Jon Pipitone <notifications@github.com>
wrote:

> Hmm, here's what we're thinking as a workaround for now: use PickTracts to
> create groups of clusters, and I'll write a small converter that dumps out
> a MRML file compatible with hierarchies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ljod/whitematteranalysis/issues/13#issuecomment-70899239>
> .
>
> The information in this e-mail is intended only for the person to whom it
> is
> addressed. If you believe this e-mail was sent to you in error and the
> e-mail
> contains patient information, please contact the Partners Compliance
> HelpLine at
> http://www.partners.org/complianceline . If the e-mail was sent to you in
> error
> but does not contain patient information, please contact the sender and
> properly
> dispose of the e-mail.
>


-- 
Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu
