### ISSUE TITLE
Fiber Tract Measurement Module

### ISSUE THREAD

**Issue by tinabehdinan** [ljod/whitematteranalysis#16]
Hi Lauren,

I was wondering if you could explain how the fiber tract measurement module works? Does this step come after the wm_separate_clusters_by_hemisphere.py script? I'm a little confused on how to operate it, so any instructions would be much appreciated.

Thanks,

Tina

**Comment by ljod** [comment]
Hi Tina. We have just updated the measurements module as follows:
The changes to the interface are:

1. If you run inside slicer you don't need to select external mrml file. Just select the hierarchy node in your slicer scene.

2. If you run it as a stand along CLI the syntax is like this:
--inputtype Fibers_Hierarchy --fiberHierarchy <your-mrml-scene-file.mrml>#<you-top-hierarchy-node-id> --inputdirectory . --outputfile <your-output-text-file.txt> --format Row_Hierarchy --separator Tab  

for example:
--inputtype Fibers_Hierarchy --fiberHierarchy scene1.mrml#vtkMRMLModelHierarchyNode1 --inputdirectory . --outputfile out1.txt --format Row_Hierarchy --separator Tab  

This change should be available in tomorrow's nightly.

**Comment by ljod** [comment]
Also, the separation script is optional, and if used would come before the measurement step.

**Comment by tinabehdinan** [comment]
Hi Lauren,

I'm curious what the function of the # is in the command line you've
written?
Also, I'm not sure if this will be changed in tomorrow's nightly, but right
now it looks like it's necessary to also enter --mrmlSceneFile when running
the FiberTractMeasurements command.

Thanks for your help,

Tina

**Comment by ljod** [comment]
Yes this should change in tomorrow's nightly.

The # is specifying which node in the file is the one to measure from (so
if you want to measure from the whole hierarchy, you put the root node
there). If you use it from Slicer's GUI you don't have to worry about that
command line information.

Lauren

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by tinabehdinan** [comment]
​
 H170_CAMH_vtklabelled.tar.gz
<https://docs.google.com/file/d/0B2Ja7BA8vx3iSFRGSGpVTmFCdWs/edit?usp=drive_web>
​So we're finding that even when we use Slicer's GUI we're not able to
extract any data from the model hierarchies. For the subject H170_CAMH
(attached) we did the following:
- create model hierarchy in models module with clusters 00244-00247
- in fiber tract scalar measurements module, input type = Fibers_Hierarchy,
fibers hierarchy = model hierarchy, output format = row_hierarchy, output
field separator = tab > Apply

The output file created is always empty - not sure why this is. Any help
would be appreciated!

**Comment by ljod** [comment]
I have tested and I also get a blank text file that just says "Name"

It does work when measuring from the directory--could you please test if
that works for you?

I am letting the developer know so we can look into this bug. Thank you.
Lauren

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by ljod** [comment]
We have replicated the issue and the developer is looking into it. It will
take at least a few days to fix.

Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by ljod** [comment]
This should be fixed in the nightly version of Slicer.

On Thursday, February 26, 2015, Lauren O'Donnell <odonnell@bwh.harvard.edu>
wrote:

> We have replicated the issue and the developer is looking into it. It will
> take at least a few days to fix.
>
> Dr. Lauren O’Donnell
> Assistant Professor, Harvard Medical School
> http://scholar.harvard.edu/laurenjodonnell
> 1249 Boylston St., Room #210
> Boston, Massachusetts 02215
> odonnell@bwh.harvard.edu
> <javascript:_e(%7B%7D,'cvml','odonnell@bwh.harvard.edu');>
>
> On Wed, Feb 25, 2015 at 3:30 PM, Lauren O'Donnell <
> odonnell@bwh.harvard.edu
> <javascript:_e(%7B%7D,'cvml','odonnell@bwh.harvard.edu');>> wrote:
>
>> I have tested and I also get a blank text file that just says "Name"
>>
>> It does work when measuring from the directory--could you please test if
>> that works for you?
>>
>> I am letting the developer know so we can look into this bug. Thank you.
>> Lauren
>>
>> Dr. Lauren O’Donnell
>> Assistant Professor, Harvard Medical School
>> http://scholar.harvard.edu/laurenjodonnell
>> 1249 Boylston St., Room #210
>> Boston, Massachusetts 02215
>> odonnell@bwh.harvard.edu
>> <javascript:_e(%7B%7D,'cvml','odonnell@bwh.harvard.edu');>
>>
>> On Mon, Feb 23, 2015 at 11:44 AM, tinabehdinan <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>>> ​
>>> H170_CAMH_vtklabelled.tar.gz
>>> <
>>> https://docs.google.com/file/d/0B2Ja7BA8vx3iSFRGSGpVTmFCdWs/edit?usp=drive_web
>>> >
>>> ​So we're finding that even when we use Slicer's GUI we're not able to
>>> extract any data from the model hierarchies. For the subject H170_CAMH
>>> (attached) we did the following:
>>> - create model hierarchy in models module with clusters 00244-00247
>>> - in fiber tract scalar measurements module, input type =
>>> Fibers_Hierarchy,
>>> fibers hierarchy = model hierarchy, output format = row_hierarchy, output
>>> field separator = tab > Apply
>>>
>>> The output file created is always empty - not sure why this is. Any help
>>> would be appreciated!
>>>
>>>
>>> On Fri, Feb 20, 2015 at 3:37 PM, ljod <notifications@github.com
>>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>>
>>> > Yes this should change in tomorrow's nightly.
>>> >
>>> > The # is specifying which node in the file is the one to measure from
>>> (so
>>> > if you want to measure from the whole hierarchy, you put the root node
>>> > there). If you use it from Slicer's GUI you don't have to worry about
>>> that
>>> > command line information.
>>> >
>>> > Lauren
>>> >
>>> > Dr. Lauren O’Donnell
>>> > Assistant Professor, Harvard Medical School
>>> > http://scholar.harvard.edu/laurenjodonnell
>>> > 1249 Boylston St., Room #210
>>> > Boston, Massachusetts 02215
>>> > odonnell@bwh.harvard.edu
>>> <javascript:_e(%7B%7D,'cvml','odonnell@bwh.harvard.edu');>
>>> >
>>> > On Fri, Feb 20, 2015 at 3:34 PM, tinabehdinan <
>>> notifications@github.com
>>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
>>> > wrote:
>>> >
>>> >
>>> > > Hi Lauren,
>>> > >
>>> > > I'm curious what the function of the # is in the command line you've
>>> > > written?
>>> > > Also, I'm not sure if this will be changed in tomorrow's nightly, but
>>> > right
>>> > > now it looks like it's necessary to also enter --mrmlSceneFile when
>>> > running
>>> > > the FiberTractMeasurements command.
>>> > >
>>> > > Thanks for your help,
>>> > >
>>> > > Tina
>>> > >
>>> > > On Fri, Feb 20, 2015 at 1:40 PM, ljod <notifications@github.com
>>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>> > >
>>> > > > Also, the separation script is optional, and if used would come
>>> before
>>> > > the
>>> > > > measurement step.
>>> > > >
>>> > > > —
>>> > > > Reply to this email directly or view it on GitHub
>>> > > > <
>>> > >
>>> >
>>> https://github.com/ljod/whitematteranalysis/issues/16#issuecomment-75295109
>>> > > >
>>> > >
>>> > > > .
>>> > > >
>>> > >
>>> > > —
>>> > > Reply to this email directly or view it on GitHub
>>> > > <
>>> >
>>> https://github.com/ljod/whitematteranalysis/issues/16#issuecomment-75314473
>>> > >
>>> > > .
>>> > >
>>> > > The information in this e-mail is intended only for the person to
>>> whom it
>>> > > is
>>> > > addressed. If you believe this e-mail was sent to you in error and
>>> the
>>> > > e-mail
>>> > > contains patient information, please contact the Partners Compliance
>>> > > HelpLine at
>>> > > http://www.partners.org/complianceline . If the e-mail was sent to
>>> you
>>> > in
>>> > > error
>>> > > but does not contain patient information, please contact the sender
>>> and
>>> > > properly
>>> > > dispose of the e-mail.
>>> >
>>> > >
>>> >
>>> > —
>>> > Reply to this email directly or view it on GitHub
>>> > <
>>> https://github.com/ljod/whitematteranalysis/issues/16#issuecomment-75314903
>>> >
>>>
>>> > .
>>> >
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ljod/whitematteranalysis/issues/16#issuecomment-75580046>
>>> .
>>>
>>
>>
>

-- 
Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by tinabehdinan** [comment]
It works! Thanks!
