### ISSUE TITLE
running wm_label_from_atlas.py - COBYLA failed to find a solution

### ISSUE THREAD

**Issue by tinabehdinan** [ljod/whitematteranalysis#17]
Hi Lauren - I keep seeing the following message when running wm_label_from_atlas.py (for all registration modes). I'm not sure if this is an error/bug that needs to be fixed or if we're not running the script properly? Please let me know.

```
<congeal.py> Computing. Registration mode: RotateOnly

   Normal return from subroutine COBYLA

   NFVALS =   15   F = 1.155452E+04    MAXCV = 1.108685E-01
   X = 5.043917E-02   7.667480E-03  -1.398708E-02  -4.539819E-02   3.419373E-03
       2.342178E-02
COBYLA failed to find a solution: Did not converge to a solution satisfying the constraints. See `maxcv` for magnitude of violation.
```

Thanks,

Tina

**Comment by ljod** [comment]
This is probably just a warning message output by the optimizer and has no
practical importance (note it says to look at the magnitude of violation of
the constraints and that magnitude is very small).

But if anything actually fails to work: What is the command line you used
to run the script? Does it succeed at producing output at the end? Does it
stop running?



Dr. Lauren O’Donnell
Assistant Professor, Harvard Medical School
http://scholar.harvard.edu/laurenjodonnell
1249 Boylston St., Room #210
Boston, Massachusetts 02215
odonnell@bwh.harvard.edu

**Comment by tinabehdinan** [comment]
The command line I used was: wm_label_from_atlas.py -reg input.vtk
atlasdirectory outputdirectory

It doesn't stop running and the output was:
cluster_00001.vtp
cluster_00002.vtp
.
.
.
cluster_00247.vtp
clustered_tracts.mrml
clustered_whole_brain.vtp
view_ant.png
view_inf.png
view_left.png
view_post.png
view_right.png
view_sup.png

**Comment by ljod** [comment]
It looks like it worked, then. This is not a bug.
