### ISSUE TITLE
utf-8 character causes syntax error

### ISSUE THREAD

**Issue by pnlbwh** [ljod/whitematteranalysis#34]
```
import whitematteranalysis
Importing whitematteranalysis package.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/__init__.py", line 4, in <module>
    exec 'import %s'%m
  File "<string>", line 1, in <module>
  File "/projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py", line 317
SyntaxError: Non-ASCII character '\xe2' in file /projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py on line 317, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
There are \xe2 characters in some comment lines, and the syntax error is avoided by replacing them with a single ASCII quote.

```
find . -name "*.py" -exec grep -iH "’" {} \;
./whitematteranalysis/register_two_subjects.py:            # Powell’s method is a conjugate direction method.
./whitematteranalysis/register_two_subjects_nonrigid.py:            # Powell’s method is a conjugate direction method.
./whitematteranalysis/register_two_subjects_nonrigid_bsplines.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects_nonrigid.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py:            # Powell’s method is a conjugate direction method.
```

Ryan

**Comment by ljod** [comment]
Thanks Ryan.

I haven't seen this error before, so it's good you found it.

Could you make a github pull request with these changes?

Lauren



On Sat, Feb 13, 2016 at 12:40 AM -0800, "pnlbwh" <notifications@github.com<mailto:notifications@github.com>> wrote:


import whitematteranalysis Importing whitematteranalysis package. Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/__init__.py",
 line 4, in <module> exec 'import %s'%m File "<string>", line 1, in <module> File "/projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py", line 317 SyntaxError: Non-ASCII character
 '\xe2' in file /projects/schiz/software/anaconda/envs/py27/lib/python2.7/site-packages/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py on line 317, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

There are \xe2 characters in some comment lines, and the syntax error is avoided by replacing them with a single ASCII quote.

find . -name "*.py" -exec grep -iH "’" {} \;
./whitematteranalysis/register_two_subjects.py:            # Powell’s method is a conjugate direction method.
./whitematteranalysis/register_two_subjects_nonrigid.py:            # Powell’s method is a conjugate direction method.
./whitematteranalysis/register_two_subjects_nonrigid_bsplines.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects_nonrigid.py:            # Powell’s method is a conjugate direction method.
./build/lib.linux-x86_64-2.7/whitematteranalysis/register_two_subjects_nonrigid_bsplines.py:            # Powell’s method is a conjugate direction method.


Ryan

—
Reply to this email directly or view it on GitHub<https://github.com/ljod/whitematteranalysis/issues/34>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by ljod** [comment]
Hi Ryan. Thanks for this information. It should be fixed. Please let me know if it works on your end, as I cannot duplicate the error here (your python must be more strict in checking this).
